### ISSUE TITLE
callpeak_idr not working

### ISSUE THREAD

**Issue by mcsimenc** [Boyle-Lab/F-Seq2#13]
I have been unable to run `callpeak_idr`.

1. Is no longer compatible with numpy >= 1.20.0.
2. Even with the compatible versions it fails with an error

`callpeak` runs ok.

Here is a summary:

Installed version of numpy on my computer:

```
numpy                     1.26.4           py39h474f0d3_0    conda-forge
```

The call and error

```
fseq2 callpeak_idr \
    -o test/callpeak_idr \
    -control_file_1 ctl_rep1.bam bam ctl_rep2.bam \
    -control_file_2 ctl_rep1.bam bam ctl_rep2.bam  \
    -name_1 rep1 \
    -name_2 rep2 \
    -standard_narrowpeak \
    -v \
    -l 50 \
    -t 8 \
    -tp 4 \
    -cpus 28 \
    -pe \
    --plot rep1_rep2.IDR.png
    tf_rep1.bam \
    tf_rep2.bam \
    >callpeak_idr.out 2>callpeak_idr.err

```

```
#3: Done
-------------------------------------
Thanks for using F-seq2.0.3!

Workflow#4: idr2.0.3 with samples(1,2), oracle peak list(3)
Traceback (most recent call last):
  File "/home/msimenc/software/mambaforge/envs/fastq2peaks/bin/fseq2", line 440, in <module>
    main(temp_dir_name)
  File "/home/msimenc/software/mambaforge/envs/fastq2peaks/bin/fseq2", line 54, in main
    submain(args)
  File "/home/msimenc/software/mambaforge/envs/fastq2peaks/lib/python3.9/site-packages/fseq2/callpeak_idr_main.py", line 60, in main
    idr_main(args)
  File "/home/msimenc/software/mambaforge/envs/fastq2peaks/lib/python3.9/site-packages/fseq2/idr_main.py", line 20, in main
    r1, r2 = build_rank_vectors(merged_peaks)
  File "/home/msimenc/software/mambaforge/envs/fastq2peaks/lib/python3.9/site-packages/fseq2/idr_2_0_3/idr.py", line 302, in build_rank_vectors
    return ( numpy.array(rank1, dtype=numpy.int),
  File "/home/msimenc/software/mambaforge/envs/fastq2peaks/lib/python3.9/site-packages/numpy/__init__.py", line 324, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
```

I created a new environment and followed the conda instructions on the install page:

```
conda install -c bioconda -c dmentipl -c samzhao fseq2
```

But it didn't install fseq2, so I used pip again

```
pip install fseq2
```

Now I have this version of numpy

```
numpy                     1.19.5                   pypi_0    pypi
```

But fseq2 is a different version now because it didn't recognize this argument

```
fseq2: error: unrecognized arguments: -standard_narrowpeak
```

I removed that argument, but I get a different error:

```
#3: Done
-------------------------------------
Thanks for using F-seq2.0.2!

Workflow#4: idr2.0.3 with samples(1,2), oracle peak list(3)
Initial parameter values: [0.10 1.00 0.20 0.50]
Traceback (most recent call last):
  File "/home/msimenc/software/mambaforge/envs/fastq2peaks.fseq2/bin/fseq2", line 428, in <module>
    main(temp_dir_name)
  File "/home/msimenc/software/mambaforge/envs/fastq2peaks.fseq2/bin/fseq2", line 54, in main
    submain(args)
  File "/home/msimenc/software/mambaforge/envs/fastq2peaks.fseq2/lib/python3.6/site-packages/fseq2/callpeak_idr_main.py", line 60, in main
    idr_main(args)
  File "/home/msimenc/software/mambaforge/envs/fastq2peaks.fseq2/lib/python3.6/site-packages/fseq2/idr_main.py", line 40, in main
    fix_mu=args.fix_mu, fix_sigma=args.fix_sigma)
  File "/home/msimenc/software/mambaforge/envs/fastq2peaks.fseq2/lib/python3.6/site-packages/fseq2/idr_2_0_3/idr.py", line 449, in fit_model_and_calc_local_idr
    fix_mu=fix_mu, fix_sigma=fix_sigma)
  File "/home/msimenc/software/mambaforge/envs/fastq2peaks.fseq2/lib/python3.6/site-packages/fseq2/idr_2_0_3/optimization.py", line 468, in estimate_model_params
    fix_mu=fix_mu, fix_sigma=fix_sigma)
  File "/home/msimenc/software/mambaforge/envs/fastq2peaks.fseq2/lib/python3.6/site-packages/fseq2/idr_2_0_3/optimization.py", line 420, in EMP_with_pseudo_value_algorithm
    z1 = compute_pseudo_values(r1, theta[0], theta[1], theta[3])
  File "/home/msimenc/software/mambaforge/envs/fastq2peaks.fseq2/lib/python3.6/site-packages/fseq2/idr_2_0_3/utility.py", line 46, in py_compute_pseudo_values
    -10, 10, EPS ) )
TypeError: py_cdf_i() takes 6 positional arguments but 7 were given
```

**Comment by aboyle** [comment]
I believe this was superseded by the users other issue.
