### ISSUE TITLE
idr not working, KDEpy error

### ISSUE THREAD

**Issue by mcsimenc** [Boyle-Lab/F-Seq2#14]
`fseq2 idr` fails for me due to KDEpy:

```
$ fseq2 idr \                                                                        
    --samples \                                                                    
        WRKY47_AtDNA_rep1_S5.trimmedAligned.sortedByCoord.out.noDuplicates_peaks.narrowPeak \
        WRKY47_AtDNA_rep2_S6.trimmedAligned.sortedByCoord.out.noDuplicates_peaks.narrowPeak \
    --input-file-type narrowPeak \                                                 
    --rank q.value \                                                               
    -o  . \                                                                        
    --output-file-type narrowPeak \                                                
    --log-output-file idr.log \                                                    
    --plot idr.png \                                                               
    >idr.out \                                                                     
    2>idr.err  

Traceback (most recent call last):
  File "/home/msimenc/software/mambaforge/envs/fseq2.built/bin/fseq2", line 4, in <module>
    __import__('pkg_resources').run_script('fseq2==2.0.3', 'fseq2')
  File "/home/msimenc/software/mambaforge/envs/fseq2.built/lib/python3.7/site-packages/pkg_resources/__init__.py", line 656, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/msimenc/software/mambaforge/envs/fseq2.built/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1453, in run_script
    exec(code, namespace, namespace)
  File "/home/msimenc/software/mambaforge/envs/fseq2.built/lib/python3.7/site-packages/fseq2-2.0.3-py3.7-linux-x86_64.egg/EGG-INFO/scripts/fseq2", line 10, in <module>
    from fseq2.fseq2 import __version__
  File "/home/msimenc/software/mambaforge/envs/fseq2.built/lib/python3.7/site-packages/fseq2-2.0.3-py3.7-linux-x86_64.egg/fseq2/fseq2.py", line 17, in <module>
    import KDEpy
  File "/home/msimenc/software/mambaforge/envs/fseq2.built/lib/python3.7/site-packages/KDEpy/__init__.py", line 4, in <module>
    import importlib.metadata
ModuleNotFoundError: No module named 'importlib.metadata'
```

**Comment by aboyle** [comment]
This error is due to the version of KDEpy you have installed with python3.7. If you install the current version of f-seq we explicitly address this dependency issue.
